---
title: "1. Data visualization"
output: pdf_document
date: "2024-07-10"
---

```{r opts_chunk, include=FALSE}
knitr::opts_chunk$set(tidy = TRUE
                  , fig.width = 4, fig.height = 3
                  , fig.align='center')
```

testing

```{r preliminaries}
library(ggplot2)
library(ggthemes)

cggplot <- function(...) {
  ggplot(...) +
    scale_color_colorblind()
}

theme_set(theme_few())
set.seed(123)
```

```{r libraries, message=FALSE}
library(tidyverse)
library(palmerpenguins)
```

```{r penguins}
glimpse(penguins)
```

# 1.4 Visualizing distributions

## A categorical variable

```{r barplot}
cggplot(penguins, aes(x = species)) +
  geom_bar()
```

```{r ordered_barplot}
cggplot(penguins, aes(x = fct_infreq(species))) +
  geom_bar()
```

## A numerical variable

```{r histogram, warning=FALSE}
cggplot(penguins, aes(x = body_mass_g)) +
  geom_histogram(binwidth = 200)
```

Inline code test:

`Inline code test:`

`r 2+2`

```{=latex}
$\frac{1}{2}$
```
```{r, warning=FALSE}
cggplot(penguins, aes(x = body_mass_g)) +
  geom_histogram(binwidth = 20)
```

```{r}
cggplot(penguins, aes(x = body_mass_g)) + geom_density()
```

## Exercises

### 1.

```{r}
cggplot(penguins, aes(y = species)) + geom_bar()
```

### 2.

```{r}
species_plot = cggplot(penguins, aes(x = species))

species_plot + geom_bar(color = 'red')
species_plot + geom_bar(fill = 'red')
```

The aesthetic *fill* is more useful because it changes the whole bars; as opposed to the *color* aesthetic, which only modifies the bar borders.

### 4.

```{r default_histogram}
carat_plot <- cggplot(diamonds, aes(x = carat))
carat_plot + geom_histogram()
```

```{r for_loop}
for (binwidth in 0.7^seq(0,9)) {
  histogram <- carat_plot +
    geom_histogram(binwidth = binwidth) +
    labs(title = paste('binwidth =', binwidth))
  print(histogram)
}
```

```{r}
binwidth <- 0.2
carat_plot +
    geom_histogram(binwidth = binwidth) +
    labs(title = paste('binwidth =', binwidth))
```

# 1.5 Visualizing relationships

## A numerical and a categorical variable

```{r}
cggplot(penguins, aes(x = body_mass_g, color = species, fill = species)) +
  geom_density(alpha = 0.5)
```

## Exercises

### 1.

```{r}
mpg
?mpg
```

### 2.

```{r}
ggplot(mpg, aes(x = hwy, y = displ)) + geom_point()
ggplot(mpg, aes(x = hwy, y = displ, color = year)) + geom_point()
ggplot(mpg, aes(x = hwy, y = displ, size = year)) + geom_point()
ggplot(mpg, aes(x = hwy, y = displ, color = year, size = year)) + geom_point()
#ggplot(mpg, aes(x = hwy, y = displ, shape = year)) + geom_point()
ggplot(mpg, aes(x = hwy, y = displ, shape = trans)) + geom_point()
```

### 3.

```{r}
ggplot(
  mpg
  , aes(
    x = hwy
    , y = displ
    )
  ) +
  geom_point(linewidth = year)

ggplot(
  mpg
  , aes(
    x = hwy
    , y = displ
    , linewidth = year
    )
  ) +
  geom_point()
```

### 5.

```{r}
cggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
  geom_point()
cggplot(penguins, aes(x = bill_depth_mm, y = bill_length_mm, color = species)) +
  geom_point() +
  facet_wrap(~species)
```

### 6.

```{r}
ggplot(
  data = penguins,
  mapping = aes(
    x = bill_length_mm, y = bill_depth_mm, 
    color = species, shape = species
  )
) +
  geom_point() +
  labs(color = "Species", shape = 'Species')
```

### 7.

```{r}
ggplot(penguins, aes(x = island, fill = species)) +
  geom_bar(position = "fill")
ggplot(penguins, aes(x = species, fill = island)) +
  geom_bar(position = "fill")
```
